services:
  moodle-db:
    image: mariadb:latest
    container_name: moodle-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    volumes:
      - dbdata:/var/lib/mysql

  moodle:
    image: moodlehq/moodle-php-apache:8.2
    container_name: moodle-web
    restart: always
    ports:
      - "8080:80"
    environment:
      MOODLE_DOCKER_DBTYPE: mariadb
      MOODLE_DOCKER_DBHOST: moodle-db
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodleuser
      MOODLE_DOCKER_DBPASS: moodlepass
    volumes:
      - moodledata:/var/moodledata
      - ../moodle:/var/www/html
volumes:
  dbdata:
  moodledata: